<?php

require_once 'config.php';

function search($search) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . ";dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $select_query = "SELECT * FROM users WHERE first_name LIKE \"%{$search}%\" OR last_name LIKE \"%{$search}%\"";
        $statement = $db->prepare($select_query);
        $statement->execute();

        if (count($statement->fetchAll())==0) {
            return 0;
        } else {
            echo "      <table>\n";
            echo "        <thead>\n";
            echo "          <tr>\n";
            echo "            <th>User ID</th>\n";
            echo "            <th>First Name</th>\n";
            echo "            <th>Last Name</th>\n";
            echo "            <th>Email</th>\n";
            echo "          </tr>\n";
            echo "        </thead>\n";
            echo "        <tbody>\n";

            // Populate the table with data coming from the database...
            foreach ($db ->query($select_query) as $row) {
                echo "          <tr>\n";
                echo "            <td>" . htmlspecialchars($row['user_id']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['first_name']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['last_name']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['email']) . "</td>\n";
                echo "          </tr>\n";
            }

            echo "         </tbody>\n";
            echo "      </table>\n";
        }
    } catch (PDOException $e) {
        echo '<p>The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";
        echo "<p>There are a few reasons for this. Perhaps the database doesn’t exist or wasn’t mounted. Does the volume/drive containing the database have read and write permissions?</p>\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';

        exit;
    }
}

function update($current_attribute, $new_attribute, $query_attribute, $pattern) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . ";dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $db -> query( "UPDATE users SET {$current_attribute}=\"{$new_attribute}\" WHERE {$query_attribute}=\"{$pattern}\"");

    } catch (PDOException $e) {
        echo '<p>The following message was generated by function <code>update</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}

function insert($first_name, $last_name, $email) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . ";dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $statement = $db->prepare("INSERT INTO users VALUES (:first_name, :last_name, :email)");
        $statement->execute(
            array(
                "first_name" => $first_name,
                "last_name" => $last_name,
                "email" => $email
            )
        );
    }catch (PDOException $e) {
        echo '<p>The following message was generated by function <code>insert</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}

function delete($current_attribute, $pattern) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . ";dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $db -> query("DELETE FROM users WHERE {$current_attribute}=\"{$pattern}\"");

    } catch (PDOException $e) {
        echo '<p>The following message was generated by function <code>delete</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}
